import type { Property } from './property-types'
import { img } from './property-types'

export const PROPERTIES: Property[] = [
  {
    id: 'royal-legend',
    name: 'Royal Legend Residence',
    area: 'kilimani',
    category: 'signature',
    type: 'apartment',
    listing: 'sale',
    status: 'bestseller',
    bedrooms: '2–5 Bedrooms + Duplex',
    price: 'From KES 14M',
    priceFrom: 14_000_000,
    description: 'Off-Plan · Ndemi Road · 2.5-Acre Master Plan · Q4 2026',
    overview:
      'Royal Legend Residence is a prestigious off-plan development along Ndemi Road in Kilimani, set on approximately 2.5 acres. The project offers spacious apartment layouts, premium finishes, expansive green spaces, and world-class lifestyle amenities for homeowners and investors seeking luxury, comfort, and long-term value.',
    image: img('Royal Legend', 'photo_2026-06-15_17-56-17.jpg'),
    imageFolder: 'Royal Legend',
    address: 'Ndemi Road, Kilimani, Nairobi',
    completion: 'Q4 2026',
    units: [
      { label: '2 Bedroom All Ensuite', size: '96 SqM', price: 'From KES 14M' },
      { label: '2 Bedroom + DSQ', size: '125 SqM', price: 'From KES 17M' },
      { label: '3 Bedroom + DSQ', size: '201–203 SqM', price: 'From KES 23.5M' },
      { label: '4 Bedroom + DSQ', size: '230 SqM', price: 'From KES 27.3M' },
      { label: '5 Bedroom + DSQ', size: '302 SqM', price: 'From KES 34.5M' },
      { label: '5 Bedroom Duplex', size: '446 SqM', price: 'From KES 62.5M' },
    ],
    highlights: [
      '18 and 19-floor residential towers',
      'Approximately 2.5-acre master-planned development',
      'Exclusive 5-bedroom duplex residences',
      'Flexible payment plans during construction',
    ],
    amenities: [
      'Olympic-size swimming pool',
      'Fully equipped gym',
      '350-meter jogging track',
      "Children's football pitch & play area",
      "Residents' clubhouse, lounge & café",
      'Library & home theatre',
      'Landscaped gardens',
      'Borehole water, backup power & CCTV',
      '24-hour security',
    ],
    investmentPoints: [
      'Prime Kilimani address with excellent connectivity',
      'High rental demand in luxury segment',
      'Strong capital appreciation potential',
      'Developed by an established developer',
    ],
    whatsappText: "Hi Sicily, I'd like to book a site visit at Royal Legend Residence, Kilimani.",
    featured: true,
  },
  {
    id: 'acacia-apartments',
    name: 'Acacia Apartments',
    area: 'kilimani',
    category: 'select',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '1–2 Bedrooms',
    price: 'From KES 7.75M',
    priceFrom: 7_750_000,
    description: 'Off-Plan · Serviced Apartments · Fully Furnished Options · June 2028',
    overview:
      'Acacia Apartments is a premium off-plan development off Nyangumi Road in Kilimani, next to the Nigerian High Commission. The project features fully furnished serviced apartments with modern finishes, hotel-style amenities, and flexible payment plans — ideal for owner-occupiers, Airbnb investors, and buy-to-let buyers.',
    image: img('Acacia', 'photo_2026-06-15_17-17-05.jpg'),
    imageFolder: 'Acacia',
    address: 'Off Nyangumi Road, Next to Nigerian High Commission, Kilimani',
    completion: 'June 2028',
    units: [
      { label: 'Standard 1BR (Furnished)', size: '59–66 SqM', price: 'KES 9.46M – 11.64M' },
      { label: '2BR (Furnished)', size: '96–99 SqM', price: 'KES 15.03M – 17.72M' },
      { label: 'Standard 1BR (Unfurnished)', size: '59–66 SqM', price: 'KES 7.75M – 8.86M' },
      { label: '2BR (Unfurnished)', size: '96–99 SqM', price: 'KES 11.96M – 14.56M' },
    ],
    highlights: [
      '20% down payment · 8% quarterly · 25-month plan',
      'Fully furnished serviced apartment model',
      'Diplomatic and commercial corridor location',
      'Strong Airbnb and long-term rental demand',
    ],
    amenities: [
      'Fully furnished units',
      '24/7 service reception',
      'Business meeting room',
      'Fully equipped gym',
      "Children's playground",
      'Infinity pool & yoga room',
      'Mini bar & restaurant',
      '24/7 security & CCTV',
      'Borehole water with purifier & backup generator',
    ],
    investmentPoints: [
      'Prime Kilimani address off Nyangumi Road',
      'Hotel-inspired lifestyle amenities',
      'High potential for capital appreciation',
      'Ideal for diaspora and expatriate tenants',
    ],
    whatsappText: "Hi Sicily, I'd like more information on Acacia Apartments, Kilimani.",
    featured: true,
  },
  {
    id: 'luminara',
    name: 'Luminara Westlands',
    area: 'westlands',
    category: 'select',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '1–2 Bedrooms',
    price: 'From KES 6.83M',
    priceFrom: 6_830_000,
    description: 'Off-Plan · Twin 24-Floor Towers · Mogotio Road · Q2 2028',
    overview:
      'Luminara Westlands is a landmark luxury development on Mogotio Road, designed around a hotel-inspired living concept. Two iconic 24-floor towers offer panoramic Nairobi skyline views, premium lifestyle amenities, and strong investment potential.',
    image: img('Luminara', 'photo_2026-06-29_15-21-13.jpg'),
    imageFolder: 'Luminara',
    address: 'Mogotio Road, Westlands, Nairobi',
    completion: 'Q2 2028',
    units: [
      { label: '1 Bedroom', size: '56 SqM', price: 'From KES 6.83M' },
      { label: '1 Bedroom', size: '65 SqM', price: 'From KES 7.23M' },
      { label: '1 Bedroom', size: '82 SqM', price: 'From KES 8.23M' },
      { label: '2 Bedroom', size: '113 SqM', price: 'From KES 11.23M' },
    ],
    highlights: [
      'Twin towers · 24 floors each',
      'Hotel-inspired lifestyle concept',
      'Rooftop infinity pool & sky lounge',
      'Flexible off-plan payment plans',
    ],
    amenities: [
      'Rooftop temperature-controlled infinity pool',
      'Sky lounge & rooftop restaurant',
      'Fully equipped gym & wellness studio',
      'Grand hotel-inspired lobby',
      'Concierge & reception services',
      'Business lounge & co-working spaces',
      'Café, mini-mart & sky gardens',
      'CCTV, access control & backup generator',
    ],
    investmentPoints: [
      'Steps from GTC, Sarit Centre & Westgate',
      'Strong rental demand in Westlands',
      'Hotel-style concept supports premium yields',
      'Landmark development with city views',
    ],
    whatsappText: "Hi Sicily, I'd like to view Luminara Westlands.",
  },
  {
    id: 'hephe-palace',
    name: 'Hephé Palace Apartments',
    area: 'westlands',
    category: 'signature',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: 'Studio – 3BR + Penthouse',
    price: 'From KES 6.2M',
    priceFrom: 6_200_000,
    description: 'Off-Plan · Ring Road · Karura Forest Views · Q3 2028',
    overview:
      'Hephé Palace is a landmark luxury high-rise along Ring Road in Westlands, minutes from Westgate Mall. Studios through penthouses offer panoramic Karura Forest and Nairobi skyline views, blending modern city living with hotel-style luxury.',
    image: img('Hephe Place', 'photo_2026-06-29_15-22-46.jpg'),
    imageFolder: 'Hephe Place',
    address: 'Ring Road, Westlands (near Westgate Mall)',
    completion: 'Q3 2028',
    units: [
      { label: 'Studio', size: '48–52 SqM', price: 'From ~KES 6.2M' },
      { label: '1 Bedroom', size: '67–87 SqM', price: 'KES 7.5M – 10.8M' },
      { label: '2 Bedroom', size: '109–130 SqM', price: 'KES 13.8M – 18.3M' },
      { label: '3 Bedroom + DSQ', size: '158–168 SqM', price: 'KES 19.8M – 22.9M' },
    ],
    highlights: [
      'Panoramic Karura Forest & skyline views',
      'Hotel-inspired concierge living',
      'Mixed unit typology for investors & end users',
      'Landmark high-rise in blue-zone Westlands',
    ],
    amenities: [
      'Heated rooftop infinity pool',
      'Fully equipped gym & yoga studio',
      'Rooftop sky garden & lounge',
      'Outdoor cinema',
      'Restaurant, café & bar',
      "Kids' play areas & family zones",
      'Business lounge & co-working spaces',
      '24/7 security, CCTV & borehole water',
    ],
    investmentPoints: [
      'Prime Ring Road location near Westgate',
      'Strong Airbnb & expatriate rental demand',
      'High capital appreciation potential',
      'Luxury amenities supporting premium rents',
    ],
    whatsappText: "Hi Sicily, I'd like floor plans and availability for Hephé Palace Apartments.",
    featured: true,
  },
  {
    id: 'citi-rise',
    name: 'Citi Rise Residency',
    area: 'westlands',
    category: 'select',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '2–3 Bedrooms + DSQ',
    price: 'From KES 11.7M',
    priceFrom: 11_700_000,
    description: 'Off-Plan · 240 Units · 24 Floors · Mogotio Road · Dec 2026/27',
    overview:
      'Citi Rise Residency is a premium 240-unit development on Mogotio Road in Westlands. Spacious 2 and 3-bedroom apartments feature contemporary finishes, panoramic city views, and lifestyle-focused amenities at competitive pricing.',
    image: img('Citi Rise', 'photo_2026-06-29_15-24-15.jpg'),
    imageFolder: 'Citi Rise',
    address: 'Mogotio Road, Westlands, Nairobi',
    completion: 'December 2026 / 2027',
    units: [
      { label: '2 Bedroom', size: '87–96 SqM', price: 'From KES 11.7M' },
      { label: '3 Bedroom', size: '115–119 SqM', price: 'From KES 15.1M' },
      { label: '3 Bedroom + DSQ', size: '140–142 SqM', price: 'From KES 17.7M' },
    ],
    highlights: [
      '240 apartments across 24 floors',
      '6 parking levels · 4 high-speed lifts',
      'Under construction with near-term completion',
      'Targeted at homeowners, investors & expatriates',
    ],
    amenities: [
      'Heated rooftop infinity pool',
      'Fully equipped gym & rooftop terrace',
      "Children's play area & yoga room",
      'Café and relaxation spaces',
      'Smart access card entry & video intercom',
      'Borehole water & full backup generator',
      'CCTV surveillance & 24-hour security',
    ],
    investmentPoints: [
      'Prime Westlands with GTC & Sarit access',
      'Strong professional & expatriate rental demand',
      'Attractive off-plan pricing',
      '240-unit scale with exclusivity',
    ],
    whatsappText: "Hi Sicily, I'd like the Citi Rise Residency brochure and payment schedule.",
  },
  {
    id: 'panorama-west',
    name: 'Panorama West Residence',
    area: 'westlands',
    category: 'select',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '1–2 Bedrooms + Penthouse',
    price: 'From KES 8M',
    priceFrom: 8_000_000,
    description: 'Off-Plan · Twin Towers · 376 Units · Opposite Safaricom House',
    overview:
      'Panorama West Residence is a contemporary twin-tower development on Mahiga Mairu Avenue, opposite Safaricom House. Spacious layouts, premium amenities, and excellent connectivity make it ideal for investors and urban professionals.',
    image: img('Panorama West', 'photo_2026-06-29_15-25-19.jpg'),
    imageFolder: 'Panorama West',
    address: 'Mahiga Mairu Avenue, Westlands (opposite Safaricom House)',
    completion: 'Q3/Q4 2027',
    units: [
      { label: '1 Bedroom', size: '69.69 SqM', price: 'From KES 8M' },
      { label: '1 Bedroom', size: '74.28 SqM', price: 'From KES 8.6M' },
      { label: '2 Bedroom', size: '111.51 SqM', price: 'From KES 12.87M' },
      { label: '3 Bedroom Penthouse + DSQ', size: '232 SqM', price: 'Price on request' },
    ],
    highlights: [
      '376 apartments · 25 floors per tower',
      '20% deposit flexible payment plan',
      'Opposite Safaricom House — prime address',
      'Competitive off-plan pricing',
    ],
    amenities: [
      'Heated swimming pool',
      'Fully equipped gym & recreation club',
      'Yoga room & reading lounge',
      'Coffee bar & children\'s playground',
      'Borehole water with purification',
      'Smart access control & landscaped areas',
    ],
    investmentPoints: [
      'Large-scale landmark in Westlands CBD',
      'Strong rental demand from professionals',
      'Excellent capital appreciation potential',
      'Premium amenities at accessible entry prices',
    ],
    whatsappText: "Hi Sicily, I'd like unit availability at Panorama West Residence.",
  },
  {
    id: 'diplomat-residencies',
    name: 'Diplomat Residencies',
    area: 'westlands',
    category: 'investment',
    type: 'apartment',
    listing: 'sale',
    status: 'bestseller',
    bedrooms: '1–2 Bedrooms',
    price: 'From KES 5M',
    priceFrom: 5_000_000,
    description: 'Off-Plan · Peponi Road · 30m from Westgate · Q1 2028',
    overview:
      'Diplomat Residencies is a landmark luxury development on Peponi Road, just 30 metres from Westgate Mall. Developed by Wonder Properties, it offers elegantly designed 1 and 2-bedroom apartments with executive living and hotel-inspired services.',
    image: img('Diplomat', 'photo_2026-06-29_15-26-05.jpg'),
    imageFolder: 'Diplomat',
    address: 'Peponi Road, Westlands, Nairobi',
    completion: 'Q1 2028',
    developer: 'Wonder Properties',
    units: [
      { label: 'Mini 1 Bedroom', size: '43 SqM', price: 'From KES 5M' },
      { label: '1 Bedroom', size: '52 SqM', price: 'From KES 6.1M' },
      { label: '1 Bedroom Deluxe', size: '76 SqM', price: 'From KES 9M' },
      { label: '1 Bedroom Executive', size: '88 SqM', price: 'From KES 10.3M' },
      { label: '2 Bedroom', size: '113 SqM', price: 'From KES 13.2M' },
      { label: '2 Bedroom Premium', size: '142 SqM', price: 'From KES 16.7M' },
    ],
    highlights: [
      '25 floors · 30 metres from Westgate Mall',
      'Hotel-inspired arrival concierge & lobby',
      'Attractive entry from KES 5M',
      'Diplomatic zone address',
    ],
    amenities: [
      'Arrival concierge & hotel-style lobby',
      'Rooftop clubhouse & infinity pool',
      'Fully equipped gym, jacuzzi & spa',
      'Tennis and padel courts',
      'Sky recreation garden',
      'Conference & business center',
      'In-building retail & laundry',
      '24/7 security & CCTV',
    ],
    investmentPoints: [
      'Nairobi\'s diplomatic & expatriate hub',
      'Strong corporate and embassy tenant demand',
      'Flexible 20% deposit payment plans',
      'High appreciation before completion',
    ],
    whatsappText: "Hi Sicily, I'd like to view Diplomat Residencies, Peponi Road.",
    featured: true,
  },
  {
    id: 'a-one-pandora',
    name: 'A-One Pandora',
    area: 'westlands',
    category: 'signature',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '2–4 Bedrooms + DSQ',
    price: 'From KES 12.91M',
    priceFrom: 12_910_000,
    description: 'Off-Plan · Muthangari Drive · 3,000 SqM Central Garden · Dec 2028',
    overview:
      'A-One Pandora is a premium off-plan development on Muthangari Drive in Westlands, opposite The Address Offices. Developed by A-One Developments, it offers luxury living, spacious layouts, and strong long-term appreciation.',
    image: img('One Pandora', 'photo_2026-06-29_15-27-32.jpg'),
    imageFolder: 'One Pandora',
    address: 'Muthangari Drive, Westlands (opposite The Address Offices)',
    completion: 'December 2028',
    developer: 'A-One Developments',
    units: [
      { label: '2 Bedroom', size: '85–109 SqM', price: 'From KES 12.91M' },
      { label: '2 Bed + Study', size: '129 SqM', price: 'From KES 19.17M' },
      { label: '3 Bed + Study + DSQ', size: '156–161 SqM', price: 'From KES 24.61M' },
      { label: '4 Bedroom + DSQ', size: '199–213 SqM', price: 'From KES 30M+' },
    ],
    highlights: [
      '3,000 sqm landscaped central garden',
      'Shopping mall within the development',
      'Heated indoor & outdoor pools',
      'Trusted developer delivery track record',
    ],
    amenities: [
      'Heated indoor & outdoor swimming pools',
      'Gym, wellness center, sauna & spa',
      'Cinema room & residents\' lounge',
      'Co-working spaces & coffee lounge',
      "Children's indoor & outdoor play areas",
      'Smart access control & 24-hour security',
    ],
    investmentPoints: [
      'Prime Muthangari Drive address',
      'Premium amenities supporting high yields',
      'Flexible off-plan payment plans',
      'Strong expatriate rental demand',
    ],
    whatsappText: "Hi Sicily, I'd like floor plans for A-One Pandora, Westlands.",
  },
  {
    id: 'gaia-brookside',
    name: 'GAIA Brookside Forest',
    area: 'westlands',
    category: 'signature',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '3–5 Bedrooms + DSQ',
    price: 'From KES 23M',
    priceFrom: 23_000_000,
    description: 'Off-Plan · Brookside Gardens · 217 Residences · 25 Floors',
    overview:
      'GAIA Brookside Forest is a prestigious luxury development on Brookside Gardens Drive in Westlands. Inspired by nature and modern urban living, it offers spacious 3, 4, and 5-bedroom residences with premium finishes and world-class amenities.',
    image: img('Gaia', 'photo_2026-06-29_15-28-31.jpg'),
    imageFolder: 'Gaia',
    address: 'Brookside Gardens Drive, Westlands, Nairobi',
    completion: '2027/2028',
    units: [
      { label: '3 Bedroom All Ensuite', size: '180 SqM', price: 'From KES 23M' },
      { label: '3 Bedroom + DSQ', size: '192–219 SqM', price: 'From KES 25.3M' },
      { label: '4 Bedroom + DSQ', size: '256–275 SqM', price: 'From KES 29M' },
      { label: '5 Bedroom + DSQ', size: '365–387 SqM', price: 'From KES 45M' },
    ],
    highlights: [
      '217 exclusive residences · 25 floors',
      'Nature-inspired Brookside address',
      'Spacious family layouts with DSQ',
      'Completion expected 2027',
    ],
    amenities: [
      'Heated infinity swimming pool',
      'Gym, wellness studio & spa with sauna',
      'Rooftop BBQ deck & sky cinema',
      'Library, lounge & daycare space',
      'Co-working & business center',
      'Smart access control & landscaped gardens',
    ],
    investmentPoints: [
      'Prestigious Brookside Gardens address',
      'High demand from expatriates & executives',
      'Luxury amenities rarely found in one development',
      'Strong capital appreciation potential',
    ],
    whatsappText: "Hi Sicily, I'd like to schedule a site visit at GAIA Brookside Forest.",
    featured: true,
  },
  {
    id: 'rhapta-one',
    name: 'Rhapta One Residency',
    area: 'westlands',
    category: 'select',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '1–2 Bedrooms + DSQ',
    price: 'From KES 7.8M',
    priceFrom: 7_800_000,
    description: 'Off-Plan · Rhapta Road · 216 Units · 2 Towers · Dec 2026',
    overview:
      'Rhapta One Residency is a modern development on Rhapta Road in Westlands, offering spacious 1 and 2-bedroom apartments with contemporary finishes and lifestyle amenities — combining affordability, convenience, and investment potential.',
    image: img('Rhapta One', 'photo_2026-06-29_15-29-25.jpg'),
    imageFolder: 'Rhapta One',
    address: 'Rhapta Road, Westlands, Nairobi',
    completion: 'December 2026',
    units: [
      { label: '1 Bedroom', size: '71 SqM', price: 'From KES 7.8M' },
      { label: '2 Bedroom', size: '110 SqM', price: 'From KES 12.8M' },
      { label: '2 Bedroom + DSQ', size: '131 SqM', price: 'From KES 14.8M' },
    ],
    highlights: [
      '2 towers · 216 apartments · 18 floors',
      'Near-term completion December 2026',
      'Affordable Westlands entry pricing',
      'Solar water heating',
    ],
    amenities: [
      'Swimming pool & fully equipped gym',
      'Rooftop garden & children\'s play area',
      'Backup generator & borehole water',
      'CCTV, intercom & 24/7 security',
    ],
    investmentPoints: [
      'Prime Rhapta Road address',
      'Strong professional rental demand',
      'Flexible off-plan payment plans',
      'Excellent connectivity to Expressway & CBD',
    ],
    whatsappText: "Hi Sicily, I'd like availability at Rhapta One Residency.",
  },
  {
    id: 'galaxy-one',
    name: 'Galaxy One',
    area: 'westlands',
    category: 'investment',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '1–3 Bedrooms',
    price: 'From KES 6.7M',
    priceFrom: 6_700_000,
    description: 'Off-Plan · Rhapta Road · 210 Units · 2 Towers · June 2027',
    overview:
      'Galaxy One is a premium off-plan development on Rhapta Road in Westlands by Lionston Real Estate. Two towers comprise 210 luxury apartments with resort-style amenities in one of Nairobi\'s most sought-after neighborhoods.',
    image: img('Galaxy', 'photo_2026-06-29_15-31-39.jpg'),
    imageFolder: 'Galaxy',
    address: 'Rhapta Road, Westlands, Nairobi',
    completion: 'June 2027',
    developer: 'Lionston Real Estate',
    units: [
      { label: '1 Bedroom', size: '57 SqM', price: 'From KES 6.7M (Cash from KES 5.6M)' },
      { label: '1 Bedroom', size: '60 SqM', price: 'From KES 6.95M (Cash from KES 5.9M)' },
      { label: '2 Bedroom', size: '83 SqM', price: 'From KES 9.94M (Cash from KES 8.4M)' },
      { label: '2 Bedroom', size: '91 SqM', price: 'From KES 10.9M (Cash from KES 9.2M)' },
      { label: '3 Bedroom', size: '142 SqM', price: 'From KES 19M (Cash from KES 14M)' },
    ],
    highlights: [
      '210 units · 14 units per floor',
      '20% deposit with balance during construction',
      'Resort-style rooftop amenities',
      'Cash purchase discounts available',
    ],
    amenities: [
      'Rooftop infinity pool & sky club',
      'Gym, yoga deck, spa & sauna',
      'Private cinema & mini golf simulator',
      'Coffee lounge, BBQ & co-working spaces',
      'Landscaped rooftop & ground gardens',
    ],
    investmentPoints: [
      'Prime Rhapta Road, Westlands',
      'Flexible payment with 20% deposit',
      'Premium amenities vs. competing developments',
      'Attractive rental yields',
    ],
    whatsappText: "Hi Sicily, I'd like to secure a unit at Galaxy One, Westlands.",
  },
  {
    id: 'mogotio-oasis',
    name: 'Mogotio Oasis',
    area: 'westlands',
    category: 'select',
    type: 'apartment',
    listing: 'sale',
    status: 'new',
    bedrooms: 'Studio – 3 Bedrooms',
    price: 'From KES 5.8M',
    priceFrom: 5_800_000,
    description: 'Off-Plan · Behind GTC · Mogotio Road · Resort-Style Living',
    overview:
      'Mogotio Oasis is a premium off-plan development on Mogotio Road in Westlands, just behind the Global Trade Centre. The project blends luxury living, modern convenience, and strong investment potential in Nairobi\'s most vibrant district.',
    image: img('Mogotio Oasis', 'photo_2026-06-29_15-32-42.jpg'),
    imageFolder: 'Mogotio Oasis',
    address: 'Mogotio Road, Westlands (behind GTC)',
    units: [
      { label: 'Studio', size: 'From 37 SqM', price: 'From KES 5.8M' },
      { label: '1 Bedroom', size: 'From 59 SqM', price: 'From KES 7.8M' },
      { label: '2 Bedroom', size: 'From 92 SqM', price: 'From KES 11.8M' },
      { label: '3 Bedroom', size: 'From 135 SqM', price: 'From KES 14.8M' },
    ],
    highlights: [
      'Behind GTC · near Sarit & Westgate',
      '5-tier automated parking system',
      'Geothermally heated infinity pool',
      '20% deposit flexible payment plans',
    ],
    amenities: [
      'Geothermally heated infinity pool',
      'Fully equipped gym & golf putting green',
      'Yoga & wellness room',
      "Residents' café & club lounge",
      'Co-working spaces & landscaped gardens',
      'Smart biometric security & CCTV',
    ],
    investmentPoints: [
      'Limited land availability in Westlands',
      'High demand from professionals & expatriates',
      'Strong capital appreciation potential',
      'Suitable for rental income & end-use',
    ],
    whatsappText: "Hi Sicily, I'd like the Mogotio Oasis price list and site visit.",
    featured: true,
  },
  {
    id: 'cheval-riverside',
    name: 'Cheval Riverside',
    area: 'riverside',
    category: 'select',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '1–2 Bedrooms + Study',
    price: 'From KES 8.3M',
    priceFrom: 8_300_000,
    description: 'Off-Plan · Riverside Drive · Opposite The Cube · 20 Floors · 2028',
    overview:
      'Cheval Riverside is a premium off-plan development on Riverside Drive in Westlands, directly opposite The Cube. Modern 1 and 2-bedroom apartments are designed for strong capital appreciation and rental returns in Nairobi\'s Blue Zone.',
    image: img('Cheval', 'photo_2026-06-29_15-33-57.jpg'),
    imageFolder: 'Cheval',
    address: 'Riverside Drive, Westlands (opposite The Cube)',
    completion: '2028',
    units: [
      { label: '1 Bedroom Luxury', size: '62–70 SqM', price: 'From KES 8.3M' },
      { label: '1 Bedroom + Study Platinum', size: '79–82 SqM', price: 'From KES 11.5M' },
      { label: '2 Bedroom Luxury', size: '110–129 SqM', price: 'From KES 14M' },
      { label: '2 Bedroom + Study Platinum', size: '124–138 SqM', price: 'From KES 18M' },
    ],
    highlights: [
      '20-floor landmark on Riverside Drive',
      'Natural-light glass prism design',
      'Pre-launch pricing available',
      'Blue Zone investment location',
    ],
    amenities: [
      'Rooftop swimming pool & sky deck',
      'Fully equipped gym & rooftop lounge',
      'Borehole water & backup generator',
      'CCTV, access control & landscaped areas',
    ],
    investmentPoints: [
      'Prime Riverside Drive address',
      'High expatriate & professional demand',
      'Strong pre-completion appreciation',
      'Flexible construction payment plans',
    ],
    whatsappText: "Hi Sicily, I'd like to view Cheval Riverside on Riverside Drive.",
  },
  {
    id: 'golden-mansion',
    name: 'Golden Mansion',
    area: 'westlands',
    category: 'signature',
    type: 'apartment',
    listing: 'sale',
    status: 'bestseller',
    bedrooms: '3–4 Bedrooms',
    price: 'From KES 12.5M',
    priceFrom: 12_500_000,
    description: 'Off-Plan · Westlands · Iconic Architecture · Rooftop Pool',
    overview:
      'Golden Mansion is an iconic luxury development in Westlands offering seamless access to Sarit Centre, Westgate, GTC, and the Nairobi Expressway. World-class amenities and premium interiors make it a lifestyle and investment destination.',
    image: img('Golden mansion', 'photo_2026-06-29_15-36-00.jpg'),
    imageFolder: 'Golden mansion',
    address: 'Westlands, Nairobi',
    units: [
      { label: '3 Bedroom', size: 'Premium layout', price: 'From KES 12.5M' },
      { label: '4 Bedroom', size: 'Premium layout', price: 'Price on request' },
    ],
    highlights: [
      'Iconic architecture in prime Westlands',
      '5-level parking podium',
      'Spacious open-plan premium interiors',
      'Strong Airbnb & long-term rental potential',
    ],
    amenities: [
      'Heated rooftop swimming pool',
      'Fully equipped gym & sky lounge',
      "Children's play area & landscaped greens",
      'Mini-mart & high-speed elevators',
      'Backup generator & 24-hour security',
    ],
    investmentPoints: [
      'Central Westlands location',
      'Strong expatriate & corporate tenant demand',
      'Flexible off-plan payment structures',
      'High capital appreciation potential',
    ],
    whatsappText: "Hi Sicily, I'd like pricing and floor plans for Golden Mansion.",
    featured: true,
  },
  {
    id: 'montbleu',
    name: 'Montbleu',
    area: 'westlands',
    category: 'select',
    type: 'apartment',
    listing: 'sale',
    status: 'bestseller',
    bedrooms: '1–2 Bedrooms',
    price: 'From KES 6.75M',
    priceFrom: 6_750_000,
    description: 'Off-Plan · Muthithi Road · Smart Home · Hotel-Style · Nov 2027',
    overview:
      'Montbleu on Muthithi Road in Westlands combines contemporary architecture, hotel-style amenities, and smart-home features. A landmark luxury development designed for modern urban living and high-yield investment.',
    image: img('Montbleu', 'photo_2026-06-29_15-35-04.jpg'),
    imageFolder: 'Montbleu',
    address: 'Muthithi Road, Westlands, Nairobi',
    completion: 'November 2027',
    units: [
      { label: 'Standard 1 Bedroom', size: '60 SqM', price: 'From KES 6.75M' },
      { label: 'Premium 1 Bedroom', size: '61 SqM', price: 'From KES 6.95M' },
      { label: 'Standard 2 Bedroom', size: '104 SqM', price: 'From KES 11.85M' },
      { label: 'Premium 2 Bedroom', size: '116 SqM', price: 'From KES 12.95M' },
    ],
    highlights: [
      'Smart home features throughout',
      'Hotel-inspired rooftop amenities',
      'Strong short-stay & long-term rental demand',
      'Prime Muthithi Road address',
    ],
    amenities: [
      'Rooftop pool & gym',
      'Sky lounge & social clubhouse',
      'Restaurant, café & mini-mart',
      'Spa & beauty lounge',
      'Solar water heating & 24/7 security',
    ],
    investmentPoints: [
      'Westlands prime corridor',
      'Capital appreciation as area develops',
      'Ideal for rental income opportunities',
      'Hotel-style living concept',
    ],
    whatsappText: "Hi Sicily, I'd like to view Montbleu, Westlands.",
    featured: true,
  },
  {
    id: 'amethyst-springs',
    name: 'Amethyst Springs',
    area: 'kilimani',
    category: 'select',
    type: 'apartment',
    listing: 'sale',
    status: 'new',
    bedrooms: '2–3 Bedrooms',
    price: 'From KES 9.2M',
    priceFrom: 9_200_000,
    description: 'Kilimani · 2–3 Bedrooms · Rooftop Lounge · Premium Finishes',
    overview:
      'Amethyst Springs offers Kilimani luxury living with thoughtfully designed 2 and 3-bedroom residences, rooftop entertainment spaces, and premium finishes in one of Nairobi\'s most established residential markets.',
    image: img('Amethyst', '250908_D02_Rooftop Bar_V1_Op1-EMETHYST.jpg'),
    imageFolder: 'Amethyst',
    address: 'Kilimani, Nairobi',
    highlights: [
      'Rooftop lounge & bar',
      'Prime Kilimani location',
      'Premium imported finishes',
    ],
    amenities: [
      'Rooftop lounge',
      'Modern fitness facilities',
      'Landscaped common areas',
      '24-hour security',
    ],
    investmentPoints: [
      'Established Kilimani rental market',
      'Strong professional tenant demand',
    ],
    whatsappText: "Hi Sicily, I'd like to view Amethyst Springs, Kilimani.",
  },
  {
    id: 'ivy-park',
    name: 'Ivy Park',
    area: 'kilimani',
    category: 'investment',
    type: 'apartment',
    listing: 'sale',
    status: 'offplan',
    bedrooms: '1–2 Bedrooms',
    price: 'From KES 6.8M',
    priceFrom: 6_800_000,
    description: 'Off-Plan · Kilimani · 1–2 Bedrooms · Modern Finishes',
    overview:
      'Ivy Park is a modern off-plan development in Kilimani offering compact 1 and 2-bedroom apartments with contemporary finishes — an accessible entry point into one of Nairobi\'s strongest rental markets.',
    image: img('Ivy Park', '1072801d-c49e-4171-bca6-7fb00f4aeb06.jpg'),
    imageFolder: 'Ivy Park',
    address: 'Kilimani, Nairobi',
    highlights: [
      'Accessible Kilimani entry pricing',
      'Modern contemporary finishes',
      'Strong rental demand area',
    ],
    amenities: [
      'Swimming pool',
      'Gym & landscaped areas',
      '24-hour security',
    ],
    investmentPoints: [
      'Kilimani rental yield potential',
      'Ideal for first-time investors',
    ],
    whatsappText: "Hi Sicily, I'd like to view Ivy Park, Kilimani.",
  },
]

export const BEST_SELLERS: Property[] = PROPERTIES.filter(p => p.featured)

export function getPropertyById(id: string): Property | undefined {
  return PROPERTIES.find(p => p.id === id)
}

export const AREA_LABELS: Record<Property['area'], string> = {
  kilimani: 'Kilimani',
  westlands: 'Westlands',
  kileleshwa: 'Kileleshwa',
  lavington: 'Lavington',
  riverside: 'Riverside',
}

export const CATEGORY_LABELS: Record<Property['category'], string> = {
  signature: 'Signature Collection',
  select: 'Select Residences',
  investment: 'Investment Entry',
}
